{% set name = "data-science-utils" %}
  {% set version = "1.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/idanmoradarthas/DataScienceUtils/releases/download/{{ version }}/data_science_utils-{{ version }}.tar.gz"
  sha256: ae46411d506e4cb5c8637e490aa3017719d8196801faa2bfa3e1e54446c37f73

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - numpy>=1.26.3
    - scipy>=1.11.4
    - pandas>=2.1.4
    - matplotlib>=3.8.0
    - seaborn>=0.12.2
    - scikit-learn>=1.2.2
    - pydotplus>=2.0.2
    - joblib>=1.2.0
  run:
    - python
    - numpy>=1.26.3
    - scipy>=1.11.4
    - pandas>=2.1.4
    - matplotlib>=3.8.0
    - seaborn>=0.12.2
    - scikit-learn>=1.2.2
    - pydotplus>=2.0.2
    - joblib>=1.2.0

test:
  imports:
    - ds_utils

about:
  home: https://github.com/idanmoradarthas/DataScienceUtils
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "This project is an ensemble of methods which are frequently used in python Data Science projects."
  description: "This project is an ensemble of methods which are frequently used in python Data Science projects."
  doc_url: https://datascienceutils.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - idanmoradarthas <https://github.com/idanmoradarthas>
