{% set name = "data-science-utils" %}
  {% set version = 1.6 %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/idanmoradarthas/DataScienceUtils/releases/download/1.6/data_science_utils-1.6.tar.gz
  sha256: 822a8fa970a4bcc9d6aec899ca01012e708e2ffed35af1e85cae063b571cf817

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - joblib >=0.12
    - matplotlib >2.02
    - numpy >=1.3
    - scipy >=1.0.0
    - pandas >=0.23.0
    - pip
    - pydotplus >=2.0.2
    - python
    - scikit-learn >=0.19.0
    - seaborn >=0.8.0
  run:
    - joblib >=0.12
    - matplotlib >2.02
    - numpy >=1.3
    - scipy >=1.0.0
    - pandas >=0.23.0
    - pydotplus >=2.0.2
    - python
    - scikit-learn >=0.19.0
    - seaborn >=0.8.0

test:
  imports:
    - ds_utils

about:
  home: https://github.com/idanmoradarthas/DataScienceUtils
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "This project is an ensemble of methods which are frequently used in python Data Science projects."
  description: "This project is an ensemble of methods which are frequently used in python Data Science projects."
  doc_url: https://datascienceutils.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - idanmoradarthas <https://github.com/idanmoradarthas>
