package:
  name: data-science-utils
  version: "1.7.4"

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - numpy>=1.26.3
    - scipy>=1.11.4
    - pandas>=2.1.4
    - matplotlib>=3.8.4
    - seaborn>=0.12.2
    - scikit-learn>=1.2.2
    - pydotplus>=2.0.2
    - joblib>=1.2.0
    - plotly>=5.24.1
  run:
    - python
    - numpy>=1.26.3
    - scipy>=1.11.4
    - pandas>=2.1.4
    - matplotlib>=3.8.4
    - seaborn>=0.12.2
    - scikit-learn>=1.2.2
    - pydotplus>=2.0.2
    - joblib>=1.2.0
    - plotly>=5.24.1

test:
  imports:
    - ds_utils

about:
  home: https://github.com/idanmoradarthas/DataScienceUtils
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "This project is an ensemble of methods which are frequently used in python Data Science projects."
  description: "This project is an ensemble of methods which are frequently used in python Data Science projects."
  doc_url: https://datascienceutils.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - idanmoradarthas <https://github.com/idanmoradarthas>
