{% set name = "data-science-utils" %}
  {% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
  {% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: data.get('download_url')
  sha256: cd1df35e6456262981200a1bd59e5c13d00ae55efe3f2f6eb358adac8555b59b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - joblib >=0.12
    - matplotlib >2.02,<=3.0.3
    - numpy >=1.3
    - pandas >=0.23.0
    - pip
    - pydotplus >=2.0.2
    - python
    - scikit-learn >=0.19.0
    - seaborn >=0.8.0
  run:
    - joblib >=0.12
    - matplotlib >2.02,<=3.0.3
    - numpy >=1.3
    - pandas >=0.23.0
    - pydotplus >=2.0.2
    - python
    - scikit-learn >=0.19.0
    - seaborn >=0.8.0

test:
  imports:
    - ds_utils

about:
  home: https://github.com/idanmoradarthas/DataScienceUtils
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: "This project is an ensemble of methods which are frequently used in python Data Science projects."
  description: "This project is an ensemble of methods which are frequently used in python Data Science projects."
  doc_url: https://datascienceutils.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - idanmoradarthas <https://github.com/idanmoradarthas>
